controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    use_sim_time: true

    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    wheel_separation: 0.135
    wheel_radius: 0.030

    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_link
    enable_odom_tf: true

    cmd_vel_timeout: 1.5

    linear:
      x:
        max_velocity: 0.26
        min_velocity: -0.26
        max_acceleration: 1.0
    angular:
      z:
        max_velocity: 1.0
        min_velocity: -1.0
        max_acceleration: 2.0
